default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: bymaga_app
  password: 12345678

development:
  <<: *default
  database: rocketdisc_development

test:
  <<: *default
  database: rocketdisc_test

production:
  url: <%= ENV['DATABASE_URL'] %>
